species:
  - name: bovis
    genus: schistosoma
    abbr: S
    clade: 1
    data_label: Sbov_LT

    files:
      gff: Sbov_LT.gff3
      protein: Sbov_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: curassoni
    genus: schistosoma
    abbr: S
    clade: 1
    data_label: Scur_LT

    files:
      gff: Scur_LT.gff3
      protein: Scur_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: guineensis
    genus: schistosoma
    abbr: S
    clade: 1
    data_label: Sgui_LT

    files:
      gff: Sgui_LT.gff3
      protein: Sgui_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: haematobium
    genus: schistosoma
    abbr: S
    clade: 1
    data_label: Shae_LT

    files:
      gff: Shae_LT.gff3
      protein: Shae_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: intercalatum
    genus: schistosoma
    abbr: S
    clade: 1
    data_label: Sint_LT

    files:
      gff: Sint_LT.gff3
      protein: Sint_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: rodhaini
    genus: schistosoma
    abbr: S
    clade: 2
    data_label: Srod_LT

    files:
      gff: Srod_LT.gff3
      protein: Srod_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: mansoni
    genus: schistosoma
    abbr: S
    clade: 2
    data_label: Sman_LT

    files:
      gff: Sman_LT.gff3
      protein: Sman_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false

  - name: mansoni_braker3_reann
    genus: schistosoma
    abbr: S
    clade: 2
    data_label: Sman_braker3_LT

    files:
      gff: Sman_braker3_LT.gff3
      protein: Sman_braker3_LT.fa

    id_prefixes:
      hog: ""
      sequence: ""
      gff: ""

    skip_plot: true

  - name: japonicum
    genus: schistosoma
    abbr: S
    clade: 3
    data_label: Sjap_LT

    files:
      gff: Sjap_LT.gff3
      protein: Sjap_LT.fa

    id_prefixes:
      hog: "transcript_"
      sequence: "transcript:"
      gff: "transcript:"

    skip_plot: false